# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'windows-latest'

    variables:
    
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      solution: '**/RoundTheCode.AzureTestProject.sln'
      project: '**/RoundTheCode.AzureTestProject.csproj'


    steps:
    - task: NuGetToolInstaller@1
      name: 'NuGetToolInstaller'
      displayName: 'NuGet tool installer'


    - task: NuGetCommand@2
      name: 'NuGetRestore'
      displayName: 'NuGet restore packages'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      name: 'Tests'
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      name: 'Publish'
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '$(project)'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false

    - task: PublishBuildArtifacts@1
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'AzureTestProject'
       publishLocation: 'Container'

- stage: DeployWebsite
  displayName: 'Deploy website'
  pool:
      vmImage: windows-latest
    
  jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Winiis'
      strategy:
       runOnce:
           deploy:
            steps:
                - checkout: none

                - download: 'current'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download Build Artifacts'
                  artifact: 'AzureTestProject'
                
               
                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    EnableIIS: true
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: 'AzureTestProject'
                
                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIIS'
                  displayName: 'Deploy IIS website'                
                  inputs:
                    WebSiteName: 'AzureTestProject'
                    Package: ' D:\a\1\AzureTestProject\RoundTheCode.AzureTestProject'
                    TakeAppOfflineFlag: true
                
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS website'                     
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: 'AzureTestProject'